// CARD
export const GET_GLOBAL = 'GET_GLOBAL';
export const GET_COUNTRY = 'GET_COUNTRY';
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const FETCH_ERROR = 'FETCH_ERROR';
export const SET_LOADING = 'SET_LOADING';

// CHART
export const GET_GLOBAL_HISTORY = 'GET_GLOBAL_HISTORY';
export const GET_COUNTRY_HISTORY = 'GET_COUNTRY_HISTORY';
export const SET_BAR_CHART = 'SET_BAR_CHART';
export const SET_CHART_LOADING = 'SET_CHART_LOADING';
export const CHART_ERROR = 'CHART_ERROR';

// TABLE
export const GET_COUNTRIES_CASES = 'GET_COUNTRIES_CASES';
export const SET_COUNTRIES_CASES_LOADING = 'SET_COUNTRIES_CASES_LOADING';
export const COUNTRIES_ERROR = 'GET_COUNTRIES_ERROR';
